# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyevent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekeyevent.proto\"\x85\x01\n\rProtoKeyEvent\x12\x15\n\x08modifier\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0b\x66unctionkey\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nsendstring\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x0b\n\t_modifierB\x0e\n\x0c_functionkeyB\r\n\x0b_sendstringb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyevent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOKEYEVENT._serialized_start=19
  _PROTOKEYEVENT._serialized_end=152
# @@protoc_insertion_point(module_scope)
